name: build-images

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Print Version
        run: echo "${{ inputs.version }}"
      - name: Fail if version not set
        if: inputs.version == ''
        run: exit 1
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::194159489498:role/GithubActionsPublishHudi-RepositoryPublisherRole-10H7ABJVFNSQ9
          role-session-name: HudiPublishSession
          role-duration-seconds: 900
      - name: Set Env
        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain onehouse --domain-owner 194159489498 --query authorizationToken --output text)" >> $GITHUB_ENV
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: maven
          server-id: codeartifact
          server-username: AWS
          server-password: CODEARTIFACT_AUTH_TOKEN
      - name: Set artifact version
        run: mvn versions:set -DnewVersion="${{ inputs.version }}"
      - name: Deploy
        run: mvn deploy -am -pl ql,metastore,common,serde -DskipTests -B -ntp -T 4
